packages:
    - "packages/*"
    - "libraries/*"

catalogs:
    reactworks:
        "@mui/lab": "^5.0.0-alpha.170"
        "@mui/material": "^5.15.20"
        "@mui/x-data-grid": "^7.7.0"
        "@mui/x-date-pickers": "^7.7.0"
        "@mui/x-tree-view": "^7.7.0"
        "axios": "^1.7.2"
        "dayjs": "^1.11.11"
        "framer-motion": "^11.2.10"
        "react": "^18.3.1"
        "react-dom": "^18.3.1"
        "react-dropzone": "^14.2.3"
        "react-hook-form": "^7.51.5"
        "react-router": "^6.23.1"
        "react-router-dom": "^6.23.1"
        "sonner": "^1.5.0"
        "zod": "^3.23.8"
        "i18next": "^23.11.5"
        "i18next-browser-languagedetector": "^8.0.0"
        "i18next-resources-to-backend": "^1.2.1"
        "react-i18next": "^14.1.2"
        "color": "^4.2.3"
        "lodash": "^4.14.202"
    reactworks-dev:
        "@types/lodash": "^4.14.202"
        "@types/react": "^18.3.1"
        "@types/react-dom": "^18.3.0"
